version: "3.7"
services:
  web-php8-server:
    container_name: clicars
    build:
      dockerfile: php.Dockerfile
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - "../:/var/www/html"
    ports:
      - "1080:80"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    expose:
      - 9003
  mysql-server:
    container_name: db
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "13307:3306"
volumes:
  mysql-data:
